### ISSUE TITLE
Gingerit module not installing 

### ISSUE THREAD

**Issue by satyam8932** [KalyanMurapaka45/Script-Correction-using-Gingerit#1]
When I'm trying to install requirements then I'm getting an error which shows could not find a version errors for gingerit 

Please guide me how to fix that error.

**Comment by KalyanM45** [comment]
try pip install gingerit==0.9.0

**Comment by satyam8932** [comment]
Hi I'll try this but can you give me your email so that I can ping you if
the module doesn't work 😕 or install

Thanks
Satyam

**Comment by KalyanM45** [comment]
kalyanmurapaka274@gmail.com
